Add the ZED Wrapper and Object Detector
umrover/mrover-ros2 pull request #3
Opened 2024-09-14 02:01 UTC by jbrhm

## Summary
Closes #2 

What features did you add, bugs did you fix, etc? 
I added the ZED Wrapper and Object Detector

### Did you add documentation to the wiki?
No it is already on the wiki

## How was this code tested? 
This code is almost one for one from the original ROS branch

### Did you test this in sim? 
Yes

### Did you test this on the rover?
No, but I did test on the real life ZED

### Did you add unit tests? 
No

2024-09-14 08:20 UTC, qhdwight commented on CMakeLists.txt
> +project(mrover VERSION 2025.0.0 LANGUAGES C CXX CUDA)
Not everyone has CUDA - make sure this works on computers w/o that installed

2024-09-14 08:23 UTC, qhdwight commented on perception/zed_wrapper/zed_wrapper.bridge.cpp
> +        leftInfoMsg.width = resolution.width;
holy not clanged formatted

2024-09-14 22:57 UTC, qhdwight commented on learning/learning.hpp
> +class Learning {
Is this really "learning" if it just does a forward inference pass 🤔

2024-09-14 22:58 UTC, qhdwight commented on CMakeLists.txt
> +project(mrover VERSION 2025.0.0 LANGUAGES C CXX CUDA)
I think I used enable_language last year if zed sdk was found

2024-09-15 01:33 UTC, qhdwight commented on CMakeLists.txt
> +set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
Already in the cmake list

2024-09-15 18:02 UTC, niwhsa9 reviewed
As promised, I _will_ review any PR that ends up in my inbox.

For everyone's sake we need @qhdwight to teach me how to unsubscribe from the automatic notifications.

2024-09-15 18:02 UTC, niwhsa9 commented on perception/zed_wrapper/zed_wrapper.bridge.cu
> +        size_t i = blockIdx.x * blockDim.x + threadIdx.x;
nit: const

2024-09-15 18:02 UTC, niwhsa9 commented on launch/object_detector.launch.py
> +        parameters=[os.path.join(get_package_share_directory("mrover"), "config", "zed.yaml")],
prefer `pathlib` : 
```python
from pathlib import Path
...
p = Path(get_package_share_directory("mrover"), "config", "zed.yaml")
```

2024-09-15 18:02 UTC, niwhsa9 commented on parameter_utils/parameter.hpp
> +						if(std::holds_alternative<int*>(mData)){
Is `holds_alternative` not completely redundant here?

2024-09-15 18:02 UTC, niwhsa9 commented on parameter_utils/parameter.hpp
> +template<class... Ts> struct overload : Ts... { using Ts::operator()...; };
`std::visit` is a fucking mess lol

Just fye: https://bitbashing.io/std-visit.html

2024-09-19 02:19 UTC, alisonryckman requested changes

2024-09-19 02:19 UTC, alisonryckman commented on launch/object_detector.launch.py
Probably don't need a separate launch file for obj detector on main

2024-09-19 02:19 UTC, alisonryckman commented on perception/object_detector/object_detector.cpp
> +        std::string packagePath{"/home/john/ros2_ws/src/mrover"};
no hard coded paths please :)

2024-09-19 02:19 UTC, alisonryckman commented on launch/zed.launch.py
> +        parameters=[os.path.join(get_package_share_directory("mrover"), "config", "zed.yaml")],
Pathlib here too like Ashwin suggested

2024-09-19 02:19 UTC, alisonryckman commented on parameter_utils/parameter.hpp
This is nice, will make our code shorter

2024-09-19 18:58 UTC, merged